# dark theme (managed by theme.sh)
background            #151720
foreground            #d7dae0
selection_background  #33415e
selection_foreground  #d7dae0
cursor                #8aa2c8
cursor_text_color     #151720
url_color             #8aa2c8
color0  #1b1e2b
color8  #3b4048
color1  #f7768e
color9  #ff8b98
color2  #9ece6a
color10 #b9f27c
color3  #e0af68
color11 #f0c987
color4  #7aa2f7
color12 #9bb8ff
color5  #bb9af7
color13 #d3b8ff
color6  #7dcfff
color14 #9be3ff
color7  #a9b1d6
color15 #d7dae0
